[cubi.metadata]
pid = "https://github.com/core-unit-bioinformatics/template-metadata-files"
version = "1.7.0"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"

[cubi.workflow.template]
pid = "undefined"
system = "smk"
version = "1.4.0"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.messages_control]
disable = [ "logging-fstring-interpolation", "useless-return", "missing-module-docstring",]

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = [ "E", "F", "B", "I",]
ignore = []
unfixable = [ "B",]
